
ALTER TABLE CLIENT
ADD COLUMN creationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN mise_a_jour TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE CLIENT
DROP COLUMN "creationDate"
ALTER TABLE CLIENT
RENAME COLUMN  creationDate TO creation
